apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.backend.app }}-service
spec:
  selector:
    app: {{ .Values.backend.app }}
  ports:
  - port: 5000
    targetPort: 3000
    {{- if eq .Values.backend.service.type "NodePort" }}
    nodePort: {{ .Values.backend.service.nodePort }}
    {{- end }}