apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.frontend.app }}-service
spec:
  type: NodePort
  selector:
    app: {{ .Values.frontend.app }}
  ports:
  - port: {{ .Values.frontend.service.port }}
    nodePort: {{ .Values.frontend.service.nodePort }}
    targetPort: {{ .Values.frontend.service.port }}
