apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.db.app }}-service
spec:
  selector:
    app: {{ .Values.db.app }}
  ports:
  - port: {{ .Values.db.port }}
    targetPort: {{ .Values.db.port }}
