apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.db.app }}-deployment
spec:
  replicas: {{ .Values.db.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.db.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.db.app }}
    spec:
      containers:
      - name: {{ .Values.db.name }}
        image: {{ .Values.db.image.repository }}:{{ .Values.db.image.tag }}
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_ROOT_PASSWORD
        ports:
        - containerPort: {{ .Values.db.port }}
